/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Album: typeof import('./src/components/my/Album.vue')['default']
    AreaPicker: typeof import('./src/components/home/AreaPicker.vue')['default']
    EmptyState: typeof import('./src/components/common/EmptyState.vue')['default']
    ImgCrop: typeof import('./src/components/img-crop/img-crop.vue')['default']
    LjWaterfall: typeof import('./src/components/lj-waterfall/lj-waterfall.vue')['default']
    OrderCard: typeof import('./src/components/order/orderCard.vue')['default']
    OrderItemBody: typeof import('./src/components/order/OrderItemBody.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tab: typeof import('./src/components/my/Tab.vue')['default']
  }
}
